// src/App.tsx
import { useEffect, useMemo, useRef, useState, startTransition } from "react";
import { open, save } from "@tauri-apps/plugin-dialog";
import "./App.css";
import { MarkdownMessage } from "./components/MarkdownMessage";
import { SettingsSheet } from "./components/SettingsSheet";
import {
  appendAssistantChunk,
  buildRequestMessages,
  createEmptySession,
  findRetryTarget,
  isSettingsComplete,
  makeTitleFromContent,
  replaceSession,
  validateSettings,
} from "./lib/chatState";
import {
  abortStream,
  deleteSession as deleteSessionRecord,
  exportData,
  importData,
  loadSessions,
  loadSettings,
  saveSession,
  saveSettings,
  startChatStream,
} from "./lib/tauri";
import type {
  AppSettings,
  ChatMessage,
  ChatSession,
  StreamEvent,
} from "./types";

const DEFAULT_SETTINGS: AppSettings = {
  baseUrl: "",
  apiKey: "",
  model: "",
  systemPrompt: "",
};

function App() {
  const [settings, setSettings] = useState<AppSettings>(DEFAULT_SETTINGS);
  const [sessions, setSessions] = useState<ChatSession[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [currentRequestId, setCurrentRequestId] = useState<string | null>(null);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const sessionsRef = useRef<ChatSession[]>([]);

  useEffect(() => {
    sessionsRef.current = sessions;
  }, [sessions]);

  useEffect(() => {
    let isMounted = true;

    async function bootstrap() {
      try {
        const [loadedSettings, loadedSessions] = await Promise.all([
          loadSettings(),
          loadSessions(),
        ]);

        if (!isMounted) {
          return;
        }

        startTransition(() => {
          setSettings(loadedSettings);
          setSessions(loadedSessions);
          setActiveSessionId(loadedSessions[0]?.id ?? null);
          setLoading(false);
        });
      } catch (error) {
        if (!isMounted) {
          return;
        }

        setLoading(false);
        setErrorMessage(
          error instanceof Error ? error.message : "Failed to load app data.",
        );
      }
    }

    void bootstrap();

    return () => {
      isMounted = false;
    };
  }, []);

  const activeSession = useMemo(
    () => sessions.find((session) => session.id === activeSessionId) ?? null,
    [activeSessionId, sessions],
  );

  async function persistSession(nextSession: ChatSession) {
    setSessions((currentSessions) => replaceSession(currentSessions, nextSession));
    await saveSession(nextSession);
  }

  async function handleCreateSession() {
    const session = createEmptySession();
    startTransition(() => {
      setSessions((currentSessions) => [session, ...currentSessions]);
      setActiveSessionId(session.id);
    });
    await saveSession(session);
  }

  async function handleDeleteSession(sessionId: string) {
    const nextSessions = sessions.filter((session) => session.id !== sessionId);
    startTransition(() => {
      setSessions(nextSessions);
      setActiveSessionId((currentId) => {
        if (currentId !== sessionId) {
          return currentId;
        }

        return nextSessions[0]?.id ?? null;
      });
    });
    await deleteSessionRecord(sessionId);
  }

  async function handleSaveSettings(nextSettings: AppSettings) {
    const errors = validateSettings(nextSettings);
    if (errors.length > 0) {
      setErrorMessage(errors[0]);
      return;
    }

    setSettings(nextSettings);
    setErrorMessage(null);
    await saveSettings(nextSettings);
    setStatusMessage("Settings saved.");
    setIsSettingsOpen(false);
  }

  function ensureActiveSession(): ChatSession {
    if (activeSession) {
      return activeSession;
    }

    const session = createEmptySession();
    setSessions((currentSessions) => [session, ...currentSessions]);
    setActiveSessionId(session.id);
    void saveSession(session);
    return session;
  }

  async function runStream(
    session: ChatSession,
    userMessage: ChatMessage,
    history: ChatMessage[],
  ) {
    const requestId = crypto.randomUUID();
    const assistantMessageId = crypto.randomUUID();
    const assistantMessage: ChatMessage = {
      id: assistantMessageId,
      role: "assistant",
      content: "",
      createdAt: new Date().toISOString(),
      status: "streaming",
    };

    const titledSession =
      session.title === "Untitled"
        ? { ...session, title: makeTitleFromContent(userMessage.content) }
        : session;

    const nextSession: ChatSession = {
      ...titledSession,
      updatedAt: new Date().toISOString(),
      messages: [...history, userMessage, assistantMessage],
    };

    await persistSession(nextSession);

    const requestMessages = buildRequestMessages(nextSession.messages, settings.systemPrompt);

    setCurrentRequestId(requestId);
    setErrorMessage(null);
    setStatusMessage("Generating...");

    const onEvent = (event: StreamEvent) => {
      if (event.event === "delta") {
        const sourceSession = sessionsRef.current.find((item) => item.id === session.id);
        if (!sourceSession) {
          return;
        }

        const updatedSession = appendAssistantChunk(
          sourceSession,
          event.data.messageId,
          event.data.textChunk,
        );
        void persistSession(updatedSession);
        return;
      }

      if (event.event === "done") {
        const sourceSession = sessionsRef.current.find((item) => item.id === session.id);
        if (!sourceSession) {
          return;
        }

        const updatedSession: ChatSession = {
          ...sourceSession,
          updatedAt: new Date().toISOString(),
          messages: sourceSession.messages.map((message) =>
            message.id === event.data.messageId
              ? { ...message, status: "done" }
              : message,
          ),
        };
        void persistSession(updatedSession);
        setCurrentRequestId(null);
        setStatusMessage("Ready.");
        return;
      }

      if (event.event === "aborted") {
        const sourceSession = sessionsRef.current.find((item) => item.id === session.id);
        if (!sourceSession) {
          return;
        }

        const updatedSession: ChatSession = {
          ...sourceSession,
          updatedAt: new Date().toISOString(),
          messages: sourceSession.messages.map((message) =>
            message.id === event.data.messageId
              ? { ...message, status: "error" }
              : message,
          ),
        };
        void persistSession(updatedSession);
        setCurrentRequestId(null);
        setStatusMessage("Generation stopped.");
        return;
      }

      if (event.event === "error") {
        const sourceSession = sessionsRef.current.find((item) => item.id === session.id);
        if (!sourceSession) {
          return;
        }

        const updatedSession: ChatSession = {
          ...sourceSession,
          updatedAt: new Date().toISOString(),
          messages: sourceSession.messages.map((message) =>
            message.id === event.data.messageId
              ? { ...message, status: "error", content: event.data.message || message.content }
              : message,
          ),
        };
        void persistSession(updatedSession);
        setCurrentRequestId(null);
        setStatusMessage(null);
        setErrorMessage(event.data.message);
      }
    };

    try {
      await startChatStream({
        requestId,
        messageId: assistantMessageId,
        settings,
        messages: requestMessages,
        onEvent,
      });
    } catch (error) {
      setCurrentRequestId(null);
      setStatusMessage(null);
      setErrorMessage(
        error instanceof Error ? error.message : "Failed to start generation.",
      );
    }
  }

  async function handleSend() {
    if (!draft.trim() || currentRequestId) {
      return;
    }

    if (!isSettingsComplete(settings)) {
      setIsSettingsOpen(true);
      setErrorMessage("Configure base URL, API key, and model before chatting.");
      return;
    }

    const session = ensureActiveSession();
    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content: draft.trim(),
      createdAt: new Date().toISOString(),
      status: "done",
    };

    setDraft("");
    await runStream(session, userMessage, session.messages);
  }

  async function handleRetry() {
    if (!activeSession || currentRequestId) {
      return;
    }

    const retryTarget = findRetryTarget(activeSession);
    if (!retryTarget) {
      setErrorMessage("Nothing to retry in this conversation yet.");
      return;
    }

    const nextMessages = activeSession.messages.filter(
      (message) => message.id !== retryTarget.assistant.id,
    );
    const nextSession = {
      ...activeSession,
      updatedAt: new Date().toISOString(),
      messages: nextMessages,
    };
    await persistSession(nextSession);
    await runStream(nextSession, retryTarget.user, retryTarget.history);
  }

  async function handleStop() {
    if (!currentRequestId) {
      return;
    }

    await abortStream(currentRequestId);
  }

  async function handleExport() {
    const path = await save({
      defaultPath: "tauri-studio-export.json",
      filters: [{ name: "JSON", extensions: ["json"] }],
    });

    if (!path) {
      return;
    }

    await exportData(path);
    setStatusMessage("Data exported.");
  }

  async function handleImport() {
    const path = await open({
      multiple: false,
      filters: [{ name: "JSON", extensions: ["json"] }],
    });

    if (!path || Array.isArray(path)) {
      return;
    }

    const imported = await importData(path);
    startTransition(() => {
      setSettings(imported.settings);
      setSessions(imported.sessions);
      setActiveSessionId(imported.sessions[0]?.id ?? null);
      setErrorMessage(null);
      setStatusMessage("Data imported.");
    });
  }

  if (loading) {
    return (
      <main className="shell loading-shell">
        <div className="loading-panel">
          <p className="eyebrow">Tauri Studio</p>
          <h1>Booting local workspace</h1>
          <p>Loading settings, sessions, and app data.</p>
        </div>
      </main>
    );
  }

  return (
    <main className="shell">
      <aside className="sidebar">
        <div className="brand-block">
          <p className="eyebrow">Desktop LLM Console</p>
          <h1>Tauri Studio</h1>
          <p className="muted">
            OpenAI-compatible chat, local persistence, and streaming replies.
          </p>
        </div>

        <div className="sidebar-actions">
          <button className="primary-button" onClick={() => void handleCreateSession()}>
            New Session
          </button>
          <button className="ghost-button" onClick={() => setIsSettingsOpen(true)}>
            Settings
          </button>
          <button className="ghost-button" onClick={() => void handleExport()}>
            Export JSON
          </button>
          <button className="ghost-button" onClick={() => void handleImport()}>
            Import JSON
          </button>
        </div>

        <div className="session-list">
          {sessions.length === 0 ? (
            <div className="empty-card">
              <p>No conversations yet.</p>
              <span>Start a session and send your first prompt.</span>
            </div>
          ) : (
            sessions.map((session) => (
              <button
                key={session.id}
                className={session.id === activeSessionId ? "session-card active" : "session-card"}
                onClick={() => setActiveSessionId(session.id)}
              >
                <span>{session.title}</span>
                <small>{new Date(session.updatedAt).toLocaleString()}</small>
                <strong>{session.messages.length} messages</strong>
                <i
                  onClick={(event) => {
                    event.stopPropagation();
                    void handleDeleteSession(session.id);
                  }}
                >
                  Delete
                </i>
              </button>
            ))
          )}
        </div>
      </aside>

      <section className="chat-panel">
        <header className="chat-header">
          <div>
            <p className="eyebrow">Conversation</p>
            <h2>{activeSession?.title ?? "Select or create a session"}</h2>
          </div>
          <div className="toolbar">
            <button className="ghost-button" onClick={() => void handleRetry()}>
              Retry
            </button>
            <button
              className="ghost-button"
              disabled={!currentRequestId}
              onClick={() => void handleStop()}
            >
              Stop
            </button>
          </div>
        </header>

        <section className="status-strip">
          <div>
            <span className="status-dot" />
            <p>{statusMessage ?? "Idle"}</p>
          </div>
          {!isSettingsComplete(settings) ? (
            <small>Settings incomplete. Open the panel to configure your endpoint.</small>
          ) : (
            <small>
              {settings.model} via {settings.baseUrl}
            </small>
          )}
        </section>

        <section className="message-list">
          {activeSession?.messages.length ? (
            activeSession.messages.map((message) => (
              <article key={message.id} className={`message-card role-${message.role}`}>
                <header>
                  <span>{message.role}</span>
                  <small>{new Date(message.createdAt).toLocaleTimeString()}</small>
                  {message.status ? <em>{message.status}</em> : null}
                </header>
                <MarkdownMessage content={message.content || "_Waiting for response..._"} />
              </article>
            ))
          ) : (
            <div className="empty-stage">
              <p>Minimal by design.</p>
              <span>
                One protocol, one window, one local store. Configure the endpoint and start
                chatting.
              </span>
            </div>
          )}
        </section>

        <footer className="composer">
          <textarea
            value={draft}
            onChange={(event) => setDraft(event.currentTarget.value)}
            placeholder="Ask the model something concrete."
            rows={4}
          />
          <div className="composer-actions">
            <div>{errorMessage ? <p className="error-copy">{errorMessage}</p> : null}</div>
            <button
              className="primary-button"
              disabled={!draft.trim() || Boolean(currentRequestId)}
              onClick={() => void handleSend()}
            >
              Send
            </button>
          </div>
        </footer>
      </section>

      <SettingsSheet
        isOpen={isSettingsOpen}
        initialSettings={settings}
        onClose={() => setIsSettingsOpen(false)}
        onSave={(nextSettings) => void handleSaveSettings(nextSettings)}
      />
    </main>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import MarkdownContent from "./components/MarkdownContent.svelte";
  import {
    createConversation,
    deleteConversation,
    getBootstrap,
    renameConversation,
    saveSettings,
    streamChat,
  } from "./lib/api";
  import {
    createLocalMessage,
    DEFAULT_SETTINGS,
    makeConversationTitle,
    replaceConversation,
    updateConversation,
    validateSettings,
  } from "./lib/playground";
  import type { AppSettings, Conversation } from "./types";

  const starterCards = [
    {
      title: "Featured",
      description: "Tune prompts, system instructions, and model parameters in one focused workspace.",
    },
    {
      title: "Code and Chat",
      description: "Use a single conversation surface for coding help, debugging, and planning.",
    },
    {
      title: "Structured Responses",
      description: "Iterate on instructions and output shape without leaving the playground.",
    },
  ];

  let settings: AppSettings = { ...DEFAULT_SETTINGS };
  let conversations: Conversation[] = [];
  let activeConversationId = "";
  let draft = "";
  let loading = true;
  let savingSettings = false;
  let statusMessage = "Loading";
  let errorMessage = "";
  let lastSavedMessage = "";
  let currentAbortController: AbortController | null = null;

  $: activeConversation =
    conversations.find((conversation) => conversation.id === activeConversationId) ?? null;
  $: isConfigured = validateSettings(settings).length === 0;

  onMount(async () => {
    try {
      const bootstrap = await getBootstrap();
      settings = bootstrap.settings;
      conversations = bootstrap.conversations;
      activeConversationId = bootstrap.conversations[0]?.id ?? "";
      statusMessage = "Ready";
    } catch (error) {
      errorMessage = error instanceof Error ? error.message : "Failed to load playground.";
      statusMessage = "Offline";
    } finally {
      loading = false;
    }
  });

  function setConversation(nextConversation: Conversation) {
    conversations = replaceConversation(conversations, nextConversation);
    activeConversationId = nextConversation.id;
  }

  async function handleCreateConversation() {
    try {
      const conversation = await createConversation();
      setConversation(conversation);
      errorMessage = "";
    } catch (error) {
      errorMessage = error instanceof Error ? error.message : "Failed to create conversation.";
    }
  }

  async function handleRenameConversation(conversation: Conversation) {
    const title = window.prompt("Rename conversation", conversation.title);
    if (!title || title.trim() === conversation.title) {
      return;
    }

    try {
      const updated = await renameConversation(conversation.id, title.trim());
      conversations = replaceConversation(conversations, updated);
    } catch (error) {
      errorMessage = error instanceof Error ? error.message : "Failed to rename conversation.";
    }
  }

  async function handleDeleteConversation(conversationId: string) {
    try {
      await deleteConversation(conversationId);
      conversations = conversations.filter((conversation) => conversation.id !== conversationId);
      if (activeConversationId === conversationId) {
        activeConversationId = conversations[0]?.id ?? "";
      }
    } catch (error) {
      errorMessage = error instanceof Error ? error.message : "Failed to delete conversation.";
    }
  }

  async function handleSaveSettings() {
    const validationErrors = validateSettings(settings);
    if (validationErrors.length > 0) {
      errorMessage = validationErrors[0];
      return;
    }

    savingSettings = true;
    try {
      settings = await saveSettings(settings);
      lastSavedMessage = "Run settings saved";
      errorMessage = "";
    } catch (error) {
      errorMessage = error instanceof Error ? error.message : "Failed to save settings.";
    } finally {
      savingSettings = false;
    }
  }

  async function handleSend() {
    if (!draft.trim() || currentAbortController) {
      return;
    }

    if (!isConfigured) {
      errorMessage = "Set Base URL, API key, and model before sending.";
      return;
    }

    let conversation = activeConversation;
    if (!conversation) {
      conversation = await createConversation();
      setConversation(conversation);
    }

    const prompt = draft.trim();
    const userMessage = createLocalMessage("user", prompt, "done");
    const optimisticConversation: Conversation = {
      ...conversation,
      title: conversation.title === "New chat" ? makeConversationTitle(prompt) : conversation.title,
      updatedAt: new Date().toISOString(),
      messages: [...conversation.messages, userMessage],
    };

    setConversation(optimisticConversation);
    draft = "";
    statusMessage = "Running";
    errorMessage = "";
    lastSavedMessage = "";

    const abortController = new AbortController();
    currentAbortController = abortController;

    try {
      await streamChat({
        conversationId: optimisticConversation.id,
        input: prompt,
        signal: abortController.signal,
        onEvent: (event) => {
          if (event.event === "start") {
            conversations = updateConversation(conversations, event.data.conversationId, (current) => ({
              ...current,
              messages: [
                ...current.messages,
                {
                  id: event.data.assistantMessageId,
                  role: "assistant",
                  content: "",
                  createdAt: new Date().toISOString(),
                  status: "streaming",
                },
              ],
            }));
            return;
          }

          if (event.event === "delta") {
            conversations = updateConversation(conversations, event.data.conversationId, (current) => ({
              ...current,
              updatedAt: new Date().toISOString(),
              messages: current.messages.map((message) =>
                message.id === event.data.messageId
                  ? {
                      ...message,
                      content: `${message.content}${event.data.textChunk}`,
                      status: "streaming",
                    }
                  : message,
              ),
            }));
            return;
          }

          if (event.event === "error") {
            statusMessage = "Failed";
            errorMessage = event.data.message;
            conversations = updateConversation(conversations, event.data.conversationId, (current) => ({
              ...current,
              updatedAt: new Date().toISOString(),
              messages: current.messages.map((message) =>
                message.id === event.data.messageId
                  ? {
                      ...message,
                      status: "error",
                      content: event.data.message,
                    }
                  : message,
              ),
            }));
            return;
          }

          if (event.event === "done") {
            statusMessage = "Ready";
            conversations = updateConversation(conversations, event.data.conversationId, (current) => ({
              ...current,
              updatedAt: new Date().toISOString(),
              messages: current.messages.map((message) =>
                message.id === event.data.messageId
                  ? {
                      ...message,
                      status: "done",
                    }
                  : message,
              ),
            }));
          }
        },
      });
    } catch (error) {
      if (!abortController.signal.aborted) {
        errorMessage = error instanceof Error ? error.message : "Failed to stream response.";
        statusMessage = "Failed";
      }
    } finally {
      currentAbortController = null;
    }
  }

  function handleStop() {
    currentAbortController?.abort();
    currentAbortController = null;
    statusMessage = "Stopped";
  }
</script>

{#if loading}
  <main class="loading-shell">
    <div class="loading-card">
      <span class="eyebrow">Simple Studio</span>
      <h1>Loading local playground</h1>
      <p>Connecting the browser UI to the Rust backend running on localhost.</p>
    </div>
  </main>
{:else}
  <main class="playground-shell">
    <aside class="sidebar">
      <div class="brand">
        <div class="brand-mark">S</div>
        <div>
          <div class="brand-title">Simple Studio</div>
          <div class="brand-subtitle">Local Playground</div>
        </div>
      </div>

      <button class="nav-pill active" type="button">Playground</button>
      <button class="new-chat-button" on:click={handleCreateConversation} type="button">
        + New prompt
      </button>

      <div class="history-section">
        <div class="section-title">History</div>
        {#if conversations.length === 0}
          <div class="muted-copy">No history yet. Start with the playground composer.</div>
        {:else}
          {#each conversations as conversation}
            <div class:active={conversation.id === activeConversationId} class="history-item">
              <button
                class="history-link"
                on:click={() => {
                  activeConversationId = conversation.id;
                  errorMessage = "";
                }}
                type="button"
              >
                <span>{conversation.title}</span>
                <small>{new Date(conversation.updatedAt).toLocaleDateString()}</small>
              </button>
              <div class="history-actions">
                <button aria-label={`Rename ${conversation.title}`} on:click={() => handleRenameConversation(conversation)} type="button">
                  Rename
                </button>
                <button aria-label={`Delete ${conversation.title}`} on:click={() => handleDeleteConversation(conversation.id)} type="button">
                  Delete
                </button>
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </aside>

    <section class="main-pane">
      <header class="workspace-header">
        <div class="workspace-heading">
          <div class="toolbar-icon">≡</div>
          <div>
            <div class="eyebrow">Playground</div>
            <h1>{activeConversation?.title ?? "Explore local models"}</h1>
          </div>
        </div>
        <div class="header-status">
          <span class="status-chip">{statusMessage}</span>
          {#if lastSavedMessage}
            <span class="status-chip subtle">{lastSavedMessage}</span>
          {/if}
        </div>
      </header>

      <section class="chat-surface">
        {#if !activeConversation || activeConversation.messages.length === 0}
          <div class="welcome-panel">
            <h2>Explore local prompts</h2>
            <div class="starter-grid">
              {#each starterCards as card}
                <button class="starter-card" on:click={() => (draft = `Help me with ${card.title.toLowerCase()} in Simple Studio.`)} type="button">
                  <strong>{card.title}</strong>
                  <span>{card.description}</span>
                </button>
              {/each}
            </div>
          </div>
        {:else}
          <div class="messages">
            {#each activeConversation.messages as message}
              <article class="message-row {message.role}">
                <div class="message-badge">{message.role}</div>
                <div class="message-card">
                  <div class="message-meta">
                    <span>{new Date(message.createdAt).toLocaleTimeString()}</span>
                    <span>{message.status}</span>
                  </div>
                  <MarkdownContent content={message.content} />
                </div>
              </article>
            {/each}
          </div>
        {/if}
      </section>

      <div class="composer-shell">
        <textarea
          aria-label="Prompt"
          bind:value={draft}
          placeholder="Start typing a prompt to see what your local playground can do"
          rows="4"
        ></textarea>
        <div class="composer-footer">
          <div class="composer-hints">
            <span class="hint-chip">{settings.model || "No model configured"}</span>
            <span class="hint-chip">temp {settings.temperature.toFixed(1)}</span>
            <span class="hint-chip">{settings.stream ? "stream on" : "stream off"}</span>
          </div>
          <div class="composer-actions">
            {#if errorMessage}
              <div class="error-banner">{errorMessage}</div>
            {/if}
            {#if currentAbortController}
              <button class="ghost-button" on:click={handleStop} type="button">Stop</button>
            {/if}
            <button class="primary-button" disabled={!draft.trim()} on:click={handleSend} type="button">
              Run
            </button>
          </div>
        </div>
      </div>
    </section>

    <aside class="settings-pane">
      <div class="section-head">
        <div class="section-title">Run settings</div>
      </div>

      <div class="settings-card">
        <label>
          <span>Base URL</span>
          <input bind:value={settings.baseUrl} placeholder="https://api.openai.com" />
        </label>
        <label>
          <span>API key</span>
          <input bind:value={settings.apiKey} placeholder="sk-..." type="password" />
        </label>
        <label>
          <span>Model</span>
          <input bind:value={settings.model} placeholder="gpt-4.1-mini" />
        </label>
        <label>
          <span>System instructions</span>
          <textarea bind:value={settings.systemInstruction} rows="5" placeholder="Optional tone and style instructions for the model"></textarea>
        </label>
      </div>

      <div class="settings-card">
        <label>
          <span>Temperature</span>
          <div class="range-row">
            <input bind:value={settings.temperature} max="2" min="0" step="0.1" type="range" />
            <strong>{settings.temperature.toFixed(1)}</strong>
          </div>
        </label>
        <label>
          <span>Max output tokens</span>
          <input bind:value={settings.maxOutputTokens} min="1" type="number" />
        </label>
        <label class="toggle-row">
          <span>Streaming</span>
          <input bind:checked={settings.stream} type="checkbox" />
        </label>
      </div>

      <button class="primary-button full-width" disabled={savingSettings} on:click={handleSaveSettings} type="button">
        {savingSettings ? "Saving..." : "Save run settings"}
      </button>
    </aside>
  </main>
{/if}
